on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: hello-R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    
    env:
      _R_CHECK_CRAN_INCOMING_: false
      
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install pak and query dependencies
        shell: Rscript {0}
        run: |
          install.packages("pak", repos = "https://r-lib.github.io/p/pak/dev/")

      - name: Install dependencies
        shell: Rscript {0}
        run: |
          pak::local_install_dev_deps(upgrade = TRUE)
          pak::pkg_install("rcmdcheck")

      - name: Check
        shell: Rscript {0}
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
